controller_list:
  - name: fake_arm_left_controller
    joints:
      - lumbar_j2__leftArm_j1_joint
      - leftArm_j1__leftArm_j2_joint
      - leftArm_j2__leftArm_j3_joint
      - leftArm_j3__leftArm_j4_joint
      - leftArm_j4__leftArm_j5_joint
      - leftArm_j5__leftArm_j6_joint
      - leftArm_j6__leftArm_j7_joint
  - name: fake_gripper_left_controller
    joints:
      - leftGripper__leftGripper_thumb_joint